build_script:
  - ps: .\build.ps1
artifacts:
  - path: build/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: VKjdo0FDOKVVrhJ4zAZ6FTaRcN34YdVbaSloJP+SkJzvhq8BEERYdE/wRt1JV2I6
  on:
    branch: master
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/60d8a5088f52066c232f
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true